const municipiosPorDepartamento = {
  AMAZONAS: [
    "Leticia",
    "Puerto Nariño",
    "El Encanto",
    "La Chorrera",
    "La Pedrera",
    "La Victoria",
    "Mirití-Paraná",
    "Puerto Alegría",
    "Puerto Arica",
    "Puerto Santander",
    "Tarapacá",
  ],
  ANTIOQUIA: [
    "Ábrego",
    "Acandí",
    "Abejorral",
    "Abriaquí",
    "Medellín",
    "Bello",
    "Itagüí",
    "Rionegro",
    "Apartadó",
    "Turbo",
    "Envigado",
    "Copacabana",
    "Caucasia",
    "Caldas",
    "La Ceja",
    "Sabaneta",
    "Girardota",
    "Santa Rosa de Osos",
    "Marinilla",
    "Caucasia",
    "El Bagre",
    "Nechí",
    "Tarazá",
    "Zaragoza",
    "Caracolí",
    "Maceo",
    "Puerto Berrío",
    "Puerto Nare",
    "Puerto Triunfo",
    "Yondó",
    "Amalfi",
    "Anorí",
    "Cisneros",
    "Remedios",
    "San Roque",
    "Santo Domingo",
    "Segovia",
    "Vegachí",
    "Yalí",
    "Yolombó",
    "Angostura",
    "Belmira",
    "Briceño",
    "Campamento",
    "Carolina del Príncipe",
    "Donmatías",
    "Entrerríos",
    "Gómez Plata",
    "Guadalupe",
    "Ituango",
    "San Andrés de Cuerquia",
    "San José de la Montaña",
    "San Pedro de los Milagros",
    "Toledo",
    "Valdivia",
    "Yarumal",
    "Santa Fe de Antioquia",
    "Anzá",
    "Buriticá",
    "Caicedo",
    "Cañasgordas",
    "Dabeiba",
    "Ebéjico",
    "Frontino",
    "Giraldo",
    "Heliconia",
    "Liborina",
    "Olaya",
    "Peque",
    "San Jerónimo",
    "Sopetrán",
    "Uramita",
    "Alejandría",
    "Argelia",
    "El Carmen de Viboral",
    "Cocorná",
    "Concepción",
    "El Peñol",
    "El Retiro",
    "El Santuario",
    "Granada",
    "Guarne",
    "Guatapé",
    "La Unión",
    "Nariño",
    "San Carlos",
    "San Francisco",
    "San Luis",
    "San Rafael",
    "San Vicente Ferrer",
    "Sonsón",
    "Amagá",
    "Andes",
    "Angelópolis",
    "Betania",
    "Betulia",
    "Caramanta",
    "Ciudad Bolívar",
    "Concordia",
    "Fredonia",
    "Hispania",
    "Jardín",
    "Jericó",
    "La Pintada",
    "Montebello",
    "Pueblorrico",
    "Salgar",
    "Santa Bárbara",
    "Támesis",
    "Tarso",
    "Titiribí",
    "Urrao",
    "Valparaíso",
    "Venecia",
    "Arboletes",
    "Carepa",
    "Chigorodó",
    "Murindó",
    "Mutatá",
    "Necoclí",
    "San Juan de Urabá",
    "San Pedro de Urabá",
    "Vigía del Fuerte",
    "Barbosa",
    "La Estrella",
    "Saban",
    "San Andrés",
    "Yondó",
  ],
  ARAUCA: [
    "Arauca",
    "Arauquita",
    "Cravo Norte",
    "Fortul",
    "Puerto Rondón",
    "Saravena",
    "Tame",
  ],
  ATLÁNTICO: [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Puerto Colombia",
    "Sabanalarga",
    "Galapa",
    "Baranoa",
    "Santo Tomás",
    "Palmar de Varela",
    "Polonuevo",
    "Sabanagrande",
    "Juan de Acosta",
    "Luruaco",
    "Piojó",
    "Tubará",
    "Campo de la Cruz",
    "Candelaria",
    "Manatí",
    "Repelón",
    "Santa Lucía",
    "Suan",
    "Usiacurí",
  ],
  BOLÍVAR: [
    "Cartagena de Indias",
    "Magangué",
    "Turbaco",
    "Arjona",
    "El Carmen de Bolívar",
    "San Juan Nepomuceno",
    "San Jacinto",
    "Santa Rosa de Lima",
    "Simití",
    "Santa Catalina",
    "María La Baja",
    "San Estanislao",
    "Cicuco",
    "Clemencia",
    "Mahates",
    "San Cristóbal",
    "Achí",
    "Altos del Rosario",
    "Arenal",
    "Arroyohondo",
    "Barranco de Loba",
    "Calamar",
    "Cantagallo",
    "Córdoba",
    "El Guamo",
    "El Peñón",
    "Hatillo de Loba",
    "Margarita",
    "Montecristo",
    "Morales",
    "Norosí",
    "Pinillos",
    "Regidor",
    "Río Viejo",
    "San Fernando",
    "San Jacinto del Cauca",
    "San Martín de Loba",
    "Santa Cruz de Mompox",
    "Santa Rosa del Sur",
    "Soplaviento",
    "Talaigua Nuevo",
    "Tiquisio",
    "Villanueva",
    "Zambrano",
  ],
  BOYACÁ: [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Villa de Leyva",
    "Paipa",
    "Samacá",
    "Garagoa",
    "El Cocuy",
    "Soatá",
    "Chivor",
    "Aquitania",
    "Guateque",
    "Moniquirá",
    "Ramiriquí",
    "Tibasosa",
    "Tenza",
    "Chíquiza",
    "Chivatá",
    "Cómbita",
    "Cucaita",
    "Motavita",
    "Oicatá",
    "Siachoque",
    "Sora",
    "Soracá",
    "Sotaquirá",
    "Toca",
    "Ventaquemada",
    "Chiscas",
    "El Espino",
    "Guacamayas",
    "Güicán",
    "Panqueba",
    "Labranzagrande",
    "Miraflores",
    "Paya",
    "Pisba",
    "Berbeo",
    "Campohermoso",
    "Santa María",
    "Cubará",
    "Puerto Boyacá",
  ],
  CALDAS: [
  "Manizales",
  "La Dorada",
  "Villamaría",
  "Chinchiná",
  "Riosucio",
  "Aguadas",
  "Pensilvania",
  "Viterbo",
  "Marmato",
  "Anserma",
  "Supía",
  "Marquetalia",
  "Filadelfia",
  "La Merced",
  "Salamina",
  "Palestina",
  "Norcasia",
  "Samaná",
  "Victoria",
  "Manzanares",
  "Marulanda",
  "Pácora",
  "Aranzazu",
  "San José",
  "Risaralda",
  "Belalcázar",
],
CAQUETÁ: [
  "Florencia",
  "San Vicente del Caguán",
  "Puerto Rico",
  "El Doncello",
  "Cartagena del Chairá",
  "La Montañita",
  "El Paujil",
  "Milán",
  "Solano",
  "Solita",
  "Morelia",
  "Valparaíso",
  "San José del Fragua",
  "Curillo",
  "Belén de los Andaquíes",
  "Albania",
],
CASANARE: [
  "Yopal",
  "Aguazul",
  "Villanueva",
  "Monterrey",
  "Tauramena",
  "Maní",
  "Paz de Ariporo",
  "Trinidad",
  "Hato Corozal",
  "Orocué",
  "Nunchía",
  "Sabanalarga",
  "Támara",
  "Recetor",
  "Chámeza",
  "San Luis de Palenque",
  "La Salina",
  "Sácama",
  "Pore",
],
CAUCA: [
  "Popayán",
  "Santander de Quilichao",
  "Puerto Tejada",
  "Piendamó",
  "El Tambo",
  "Guachené",
  "Patía (El Bordo)",
  "Toribío",
  "Inzá",
  "Cajibío",
  "Silvia",
  "Timbío",
  "Villa Rica",
  "Corinto",
  "Caloto",
  "La Sierra",
  "Buenos Aires",
  "Miranda",
  "Padilla",
  "Suárez",
  "Rosas",
  "Sotará",
  "Almaguer",
  "Argelia",
  "Balboa",
  "Bolívar",
  "Florencia",
  "La Vega",
  "Mercaderes",
  "Piamonte",
  "San Sebastián",
  "Santa Rosa",
  "Sucre",
  "Guapi",
  "Timbiquí",
  "López de Micay",
  "Caldono",
  "Jambaló",
  "Páez",
  "Puracé (Coconuco)",
  "Totoró",
  "Valle del Patía",
],
CESAR: [
  "Valledupar",
  "Aguachica",
  "Bosconia",
  "Curumaní",
  "El Copey",
  "La Jagua de Ibirico",
  "Manaure Balcón del Cesar",
  "Chiriguaná",
  "El Paso",
  "Pueblo Bello",
  "San Alberto",
  "San Diego",
  "San Martín",
  "Tamalameque",
  "Pelaya",
  "Gamarra",
  "Astrea",
  "Becerril",
  "La Gloria",
  "González",
  "Río de Oro",
  "Agustín Codazzi",
  "Pailitas",
],
CHOCÓ: [
  "Quibdó",
  "Istmina",
  "Condoto",
  "Tadó",
  "Riosucio",
  "Bahía Solano",
  "Nuquí",
  "Medio Atrato",
  "Medio San Juan",
  "Alto Baudó",
  "Bajo Baudó",
  "Carmen del Darién",
  "Bojayá",
  "Acandí",
  "Unguía",
  "Lloró",
  "Bagadó",
  "El Cantón de San Pablo",
  "El Carmen de Atrato",
  "Río Quito",
  "Novita",
  "Sipí",
  "Juradó",
  "San José del Palmar",
  "Cértegui",
  "Medio Baudó",
  "El Litoral del San Juan",
],
CÓRDOBA: [
  "Montería",
  "Cereté",
  "Lorica",
  "Sahagún",
  "Montelíbano",
  "Planeta Rica",
  "Chinú",
  "Tierralta",
  "San Pelayo",
  "San Carlos",
  "Ciénaga de Oro",
  "Canalete",
  "Pueblo Nuevo",
  "Puerto Escondido",
  "Momil",
  "Los Córdobas",
  "Ayapel",
  "Buenavista",
  "Chimá",
  "Cotorra",
  "La Apartada",
  "Moñitos",
  "Purísima",
  "San Antero",
  "San Bernardo del Viento",
  "San José de Uré",
  "Santa Cruz de Lorica",
  "Tuchín",
  "Valencia",
],
CUNDINAMARCA: [
  "Bogotá D.C.",
  "Soacha",
  "Chía",
  "Zipaquirá",
  "Facatativá",
  "Mosquera",
  "Fusagasugá",
  "Girardot",
  "Madrid",
  "Funza",
  "Cajicá",
  "La Calera",
  "Villeta",
  "Tocancipá",
  "Chocontá",
  "Guaduas",
  "Anapoima",
  "Tabio",
  "Tenjo",
  "Agua de Dios",
  "Albán",
  "Anolaima",
  "Apulo",
  "Arbeláez",
  "Beltrán",
  "Bituima",
  "Cachipay",
  "Caparrapí",
  "Cáqueza",
  "Carmen de Carupa",
  "Chaguaní",
  "Chipaque",
  "Choachí",
  "Cogua",
  "Cota",
  "Cucunubá",
  "El Peñón",
  "El Rosal",
  "Fómeque",
  "Fosca",
  "Fúquene",
  "Gachalá",
  "Gachancipá",
  "Gachetá",
  "Gama",
  "Granada",
  "Guachetá",
  "Guasca",
  "Guataquí",
  "Guatavita",
  "Guayabal de Siquima",
  "Guayabetal",
  "Gutiérrez",
  "Jerusalén",
  "Junín",
  "La Mesa",
  "La Palma",
  "La Peña",
  "La Vega",
  "Lenguazaque",
  "Machetá",
  "Manta",
  "Medina",
  "Nariño",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nocaima",
  "Pacho",
  "Paime",
  "Pandi",
  "Paratebueno",
  "Pasca",
  "Puerto Salgar",
  "Pulí",
  "Quebradanegra",
  "Quetame",
  "Quipile",
  "Ricaurte",
  "San Antonio del Tequendama",
  "San Bernardo",
  "San Cayetano",
  "San Francisco",
  "San Juan de Río Seco",
  "Sasaima",
  "Sesquilé",
  "Sibaté",
  "Silvania",
  "Simijaca",
  "Subachoque",
  "Suesca",
  "Supatá",
  "Susa",
  "Sutatausa",
  "Tausa",
  "Tena",
  "Tibacuy",
  "Tibirita",
  "Tocaima",
  "Topaipí",
  "Ubalá",
  "Ubaque",
  "Ubaté",
  "Une",
  "Útica",
  "Vergara",
  "Vianí",
  "Villagómez",
  "Villapinzón",
  "Viotá",
  "Yacopí",
  "Zipacón",
],
GUAINÍA: [
  "Inírida",
  "Barranco Minas",
  "San Felipe",
  "Puerto Colombia",
  "Cacahual",
  "La Guadalupe",
  "Pana Pana",
  "Morichal",
],
GUAVIARE: ["San José del Guaviare", 
  "Calamar", 
  "El Retorno", 
  "Miraflores"
],
HUILA: [
  "Neiva",
  "Pitalito",
  "Garzón",
  "La Plata",
  "Campoalegre",
  "San Agustín",
  "Algeciras",
  "Gigante",
  "Tarqui",
  "Acevedo",
  "Palermo",
  "Timaná",
  "Villavieja",
  "Yaguará",
  "Isnos",
  "Tello",
  "Íquira",
  "Hobo",
  "Altamira",
  "Elías",
  "Guadalupe",
  "Pital",
  "Santa María",
  "Nátaga",
  "Suaza",
  "Oporapa",
  "Paicol",
  "Tesalia",
  "Saladoblanco",
  "Agrado",
  "Baraya",
  "Rivera",
  "Teruel",
],
"LA GUAJIRA": [
  "Riohacha",
  "Maicao",
  "Uribia",
  "Manaure",
  "San Juan del Cesar",
  "Dibulla",
  "Barrancas",
  "Distracción",
  "El Molino",
  "Fonseca",
  "Hatonuevo",
  "Urumita",
  "Villanueva",
  "La Jagua del Pilar",
  "Albania",
],
MAGDALENA: [
  "Santa Marta",
  "Ciénaga",
  "Fundación",
  "El Banco",
  "Plato",
  "Pivijay",
  "Aracataca",
  "Tenerife",
  "Salamina",
  "San Sebastián de Buenavista",
  "Santa Ana",
  "Remolino",
  "Zona Bananera",
  "Pueblo Viejo",
  "Sitionuevo",
  "El Piñón",
  "Santa Bárbara de Pinto",
  "Zapayán",
  "Concordia",
  "Chibolo",
  "Nueva Granada",
  "Pedraza",
  "Guamal",
  "Sabanas de San Ángel",
  "El Retén",
  "Ariguaní",
  "Cerro de San Antonio",
  "Pijiño del Carmen",
  "San Zenón",
],
META: [
  "Villavicencio",
  "Acacías",
  "Granada",
  "Puerto López",
  "Cumaral",
  "Vista Hermosa",
  "San Martín",
  "Guamal",
  "Puerto Gaitán",
  "San Carlos de Guaroa",
  "El Dorado",
  "Castilla La Nueva",
  "San Juan de Arama",
  "Restrepo",
  "La Macarena",
  "Uribe",
  "Lejanías",
  "Mapiripán",
  "Mesetas",
  "Puerto Concordia",
  "Puerto Lleras",
  "Puerto Rico",
  "Fuente de Oro",
  "Cabuyaro",
  "Barranca de Upía",
  "Rubiales",
],
NARIÑO: [
  "Pasto",
  "Tumaco",
  "Ipiales",
  "Túquerres",
  "La Unión",
  "Samaniego",
  "Barbacoas",
  "Cumbal",
  "Guachucal",
  "Mallama (Piedrancha)",
  "Los Andes",
  "El Charco",
  "Consacá",
  "La Cruz",
  "Sandona",
  "Chachagüí",
  "Colón",
  "El Rosario",
  "Belén",
  "San Lorenzo",
  "Arboleda",
  "San Pablo",
  "San Pedro de Cartago",
  "La Florida",
  "Santa Bárbara",
  "Taminango",
  "Policarpa",
  "Leiva",
  "El Tablón de Gómez",
  "Ricaurte",
  "Magüí Payán",
  "Francisco Pizarro",
  "Mosquera",
  "Olaya Herrera",
  "Roberto Payán",
  "Santa Cruz",
  "Imués",
  "Albán",
  "Aldana",
  "Cuaspud",
  "Funes",
  "Gualmatán",
  "Potosí",
  "Puerres",
  "Pupiales",
],
"NORTE DE SANTANDER": [
  "Cúcuta",
  "Ocaña",
  "Pamplona",
  "Villa del Rosario",
  "Los Patios",
  "Tibú",
  "Ábrego",
  "El Zulia",
  "Chinácota",
  "Toledo",
  "Puerto Santander",
  "San Cayetano",
  "Mutiscua",
  "Bucarasica",
  "Hacarí",
  "Sardinata",
  "El Tarra",
  "Convención",
  "La Playa de Belén",
  "San Calixto",
  "Teorama",
  "Cáchira",
  "Cacota",
  "Chitagá",
  "Silos",
  "Arboledas",
  "Durania",
  "Ragonvalia",
  "Herrán",
  "Labateca",
  "Bochalema",
  "Gramalote",
  "Salazar de las Palmas",
],
PUTUMAYO: [
  "Mocoa",
  "Puerto Asís",
  "Orito",
  "Villagarzón",
  "Puerto Leguízamo",
  "Sibundoy",
  "San Francisco",
  "San Miguel",
  "Valle del Guamuez",
  "Colón",
  "Puerto Caicedo",
  "Puerto Guzmán",
  "Santiago",
],
QUINDÍO: [
  "Armenia",
  "Calarcá",
  "La Tebaida",
  "Quimbaya",
  "Montenegro",
  "Filandia",
  "Salento",
  "Génova",
  "Circasia",
  "Pijao",
  "Córdoba",
],
RISARALDA: [
  "Pereira",
  "Dosquebradas",
  "Santa Rosa de Cabal",
  "La Virginia",
  "Belén de Umbría",
  "Apía",
  "Marsella",
  "Santuario",
  "Quinchía",
  "Mistrató",
  "Balboa",
  "Guática",
  "Pueblo Rico",
  "La Celia",
],
"SAN ANDRÉS Y PROVIDENCIA": [
  "San Andrés",
  "Providencia",
  "Santa Catalina",
  "Cayos",
],
SANTANDER: [
  "Bucaramanga",
  "Floridablanca",
  "Piedecuesta",
  "Girón",
  "Barrancabermeja",
  "San Gil",
  "Socorro",
  "Vélez",
  "Barichara",
  "Curití",
  "Zapatoca",
  "Rionegro",
  "Cimitarra",
  "Málaga",
  "Aguada",
  "Albania",
  "Aratoca",
  "Barbosa",
  "Betulia",
  "Bolívar",
  "Cabrera",
  "California",
  "Capitanejo",
  "Carcasí",
  "Cepitá",
  "Charalá",
  "Chima",
  "Chipatá",
  "Concepción",
  "Confines",
  "Contratación",
  "Coromoro",
  "El Carmen de Chucurí",
  "El Guacamayo",
  "Enciso",
  "Galán",
  "Gámbita",
  "Guaca",
  "Guadalupe",
  "Guapotá",
  "Guavatá",
  "Güepsa",
  "Hato",
  "Jesús María",
  "Jordán",
  "Landázuri",
  "Lebrija",
  "Los Santos",
  "Macaravita",
  "Matanza",
  "Mogotes",
  "Molagavita",
  "Ocamonte",
  "Oiba",
  "Onzaga",
  "Palmar",
  "Palmas del Socorro",
  "Páramo",
  "Puente Nacional",
  "Puerto Wilches",
  "Sabana de Torres",
  "San Vicente de Chucurí",
  "Santa Bárbara",
  "Simacota",
  "Suaita",
  "Suratá",
  "Tona",
  "Vetas",
  "Zapatoca",
],
SUCRE: [
  "Sincelejo",
  "Corozal",
  "San Marcos",
  "Sampués",
  "San Onofre",
  "Tolú",
  "Coveñas",
  "San Benito Abad",
  "Since",
  "Majagual",
  "Galeras",
  "Ovejas",
  "Chalán",
  "Palmito",
  "Guaranda",
  "Caimito",
  "La Unión",
  "El Roble",
  "Los Palmitos",
],
TOLIMA: [
  "Ibagué",
  "Espinal",
  "Melgar",
  "Honda",
  "Chaparral",
  "Lérida",
  "Mariquita",
  "Líbano",
  "Flandes",
  "Carmen de Apicalá",
  "Purificación",
  "Guamo",
  "Planadas",
  "Coyaima",
  "Rovira",
  "Venadillo",
  "Casabianca",
  "Santa Isabel",
],
"VALLE DEL CAUCA": [
  "Cali",
  "Palmira",
  "Buenaventura",
  "Tuluá",
  "Cartago",
  "Jamundí",
  "Buga",
  "Candelaria",
  "Zarzal",
  "Dagua",
  "Yumbo",
  "Sevilla",
  "Pradera",
  "Florida",
  "La Unión",
  "La Cumbre",
  "El Cerrito",
  "Ginebra",
  "El Dovio",
  "Restrepo",
  "Roldanillo",
  "Toro",
  "Trujillo",
  "Versalles",
  "Ansermanuevo",
],
VAUPÉS: ["Mitú", 
  "Carurú", 
  "Pacoa", 
  "Taraira", 
  "Papunaua", 
  "Yavaraté"
],
VICHADA: [
  "Puerto Carreño",
  "Cumaribo",
  "La Primavera",
  "Santa Rosalía",
],
};