const municipiosPorDepartamento = {
  AMAZONAS: ["Leticia", "Puerto Nariño"],
  ANTIOQUIA: [
    "Ábrego",
    "Acandí",
    "Abejorral",
    "Abriaquí",
    "Medellín",
    "Bello",
    "Itagüí",
    "Rionegro",
    "Apartadó",
    "Turbo",
    "Envigado",
    "Copacabana",
    "Caucasia",
    "Caldas",
    "La Ceja",
    "Sabaneta",
    "Girardota",
    "Santa Rosa de Osos",
    "Marinilla",
  ],
  ARAUCA: [
    "Arauca",
    "Arauquita",
    "Cravo Norte",
    "Fortul",
    "Puerto Rondón",
    "Saravena",
    "Tame",
  ],
  ATLÁNTICO: [
    "Barranquilla",
    "Soledad",
    "Malambo",
    "Puerto Colombia",
    "Sabanalarga",
    "Galapa",
    "Baranoa",
    "Santo Tomás",
    "Palmar de Varela",
    "Polonuevo",
    "Sabanagrande",
    "Juan de Acosta",
    "Luruaco",
    "Piojó",
    "Tubará",
  ],
  BOLÍVAR: [
    "Cartagena de Indias",
    "Magangué",
    "Turbaco",
    "Arjona",
    "El Carmen de Bolívar",
    "San Juan Nepomuceno",
    "San Jacinto",
    "Santa Rosa de Lima",
    "Simití",
    "Santa Catalina",
    "María La Baja",
    "San Estanislao",
    "Cicuco",
    "Clemencia",
    "Mahates",
    "San Cristóbal",
  ],
  BOYACÁ: [
    "Tunja",
    "Duitama",
    "Sogamoso",
    "Chiquinquirá",
    "Villa de Leyva",
    "Paipa",
    "Samacá",
    "Garagoa",
    "El Cocuy",
    "Soatá",
    "Chivor",
    "Aquitania",
    "Guateque",
    "Moniquirá",
    "Ramiriquí",
    "Tibasosa",
    "Tenza",
  ],
  CALDAS: [
    "Manizales",
    "La Dorada",
    "Villamaría",
    "Chinchiná",
    "Riosucio",
    "Aguadas",
    "Pensilvania",
    "Viterbo",
    "Marmato",
    "Anserma",
    "Supía",
    "Marquetalia",
    "Filadelfia",
    "La Merced",
    "Salamina",
    "Palestina",
  ],
  CAQUETÁ: [
    "Florencia",
    "San Vicente del Caguán",
    "Puerto Rico",
    "El Doncello",
    "Cartagena del Chairá",
    "La Montañita",
    "El Paujil",
    "Milán",
    "Solano",
    "Solita",
    "Morelia",
    "Valparaíso",
    "San José del Fragua",
    "Curillo",
    "Belén de los Andaquíes",
  ],
  CASANARE: [
    "Yopal",
    "Aguazul",
    "Villanueva",
    "Monterrey",
    "Tauramena",
    "Maní",
    "Paz de Ariporo",
    "Trinidad",
    "Hato Corozal",
    "Orocué",
    "Nunchía",
    "Sabanalarga",
    "Tamara",
    "Recetor",
    "Chámeza",
    "San Luis de Palenque",
  ],
  CAUCA: [
    "Popayán",
    "Santander de Quilichao",
    "Puerto Tejada",
    "Piendamó",
    "El Tambo",
    "Guachené",
    "Patía (El Bordo)",
    "Toribío",
    "Inzá",
    "Cajibío",
    "Silvia",
    "Timbío",
    "Villa Rica",
    "Corinto",
    "Caloto",
    "La Sierra",
  ],
  CESAR: [
    "Valledupar",
    "Aguachica",
    "Bosconia",
    "Curumaní",
    "El Copey",
    "La Jagua de Ibirico",
    "Manaure Balcón del Cesar",
    "Chiriguaná",
    "El Paso",
    "Pueblo Bello",
    "San Alberto",
    "San Diego",
    "San Martín",
    "Tamalameque",
    "Pelaya",
    "Gamarra",
  ],
  CÓRDOBA: [
    "Montería",
    "Cereté",
    "Lorica",
    "Sahagún",
    "Montelíbano",
    "Planeta Rica",
    "Chinú",
    "Tierralta",
    "San Pelayo",
    "San Carlos",
    "Ciénaga de Oro",
    "Canalete",
    "Pueblo Nuevo",
    "Puerto Escondido",
    "Momil",
    "Los Córdobas",
  ],
  CUNDINAMARCA: [
    "Bogotá D.C.",
    "Soacha",
    "Chía",
    "Zipaquirá",
    "Facatativá",
    "Mosquera",
    "Fusagasugá",
    "Girardot",
    "Madrid",
    "Funza",
    "Cajicá",
    "La Calera",
    "Villeta",
    "Tocancipá",
    "Chocontá",
    "Guaduas",
    "Anapoima",
    "Tabio",
    "Tenjo",
  ],
  GUAINÍA: [
    "Inírida",
    "Barranco Minas",
    "San Felipe",
    "Puerto Colombia",
    "Cacahual",
    "La Guadalupe",
    "Pana Pana",
    "Morichal",
  ],
  GUAVIARE: ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
  HUILA: [
    "Neiva",
    "Pitalito",
    "Garzón",
    "La Plata",
    "Campoalegre",
    "San Agustín",
    "Algeciras",
    "Gigante",
    "Tarqui",
    "Acevedo",
    "Palermo",
    "Timaná",
    "Villavieja",
    "Yaguará",
    "Isnos",
    "Tello",
  ],
  "LA GUAJIRA": [
    "Riohacha",
    "Maicao",
    "Uribia",
    "Manaure",
    "San Juan del Cesar",
    "Dibulla",
    "Barrancas",
    "Distracción",
    "El Molino",
    "Fonseca",
    "Hatonuevo",
    "Urumita",
    "Villanueva",
  ],
  MAGDALENA: [
    "Santa Marta",
    "Ciénaga",
    "Fundación",
    "El Banco",
    "Plato",
    "Pivijay",
    "Aracataca",
    "Tenerife",
    "Salamina",
    "San Sebastián de Buenavista",
    "Santa Ana",
    "Remolino",
    "Zona Bananera",
    "Pueblo Viejo",
    "Sitionuevo",
  ],
  META: [
    "Villavicencio",
    "Acacías",
    "Granada",
    "Puerto López",
    "Cumaral",
    "Vista Hermosa",
    "San Martín",
    "Guamal",
    "Puerto Gaitán",
    "San Carlos de Guaroa",
    "El Dorado",
    "Castilla La Nueva",
    "San Juan de Arama",
    "Restrepo",
    "La Macarena",
  ],
  NARIÑO: [
    "Pasto",
    "Tumaco",
    "Ipiales",
    "Túquerres",
    "La Unión",
    "Samaniego",
    "Barbacoas",
    "Cumbal",
    "Guachucal",
    "Mallama (Piedrancha)",
    "Los Andes",
    "El Charco",
    "Consacá",
    "La Cruz",
    "Sandona",
    "Chachagüí",
  ],
  "NORTE DE SANTANDER": [
    "Cúcuta",
    "Ocaña",
    "Pamplona",
    "Villa del Rosario",
    "Los Patios",
    "Tibú",
    "Abrego",
    "El Zulia",
    "Chinácota",
    "Toledo",
    "Puerto Santander",
    "San Cayetano",
    "Mutiscua",
    "Bucarasica",
    "Hacarí",
  ],
  PUTUMAYO: [
    "Mocoa",
    "Puerto Asís",
    "Orito",
    "Villagarzón",
    "Puerto Leguízamo",
    "Sibundoy",
    "San Francisco",
    "San Miguel",
    "Valle del Guamuez",
    "Colón",
  ],
  QUINDÍO: [
    "Armenia",
    "Calarcá",
    "La Tebaida",
    "Quimbaya",
    "Montenegro",
    "Filandia",
    "Salento",
    "Génova",
    "Circasia",
    "Pijao",
  ],
  RISARALDA: [
    "Pereira",
    "Dosquebradas",
    "Santa Rosa de Cabal",
    "La Virginia",
    "Belén de Umbría",
    "Apía",
    "Marsella",
    "Santuario",
    "Quinchía",
    "Mistrató",
    "Balboa",
    "Guática",
  ],
  "SAN ANDRÉS Y PROVIDENCIA": ["San Andrés", "Providencia y Santa Catalina"],
  SANTANDER: [
    "Bucaramanga",
    "Floridablanca",
    "Piedecuesta",
    "Girón",
    "Barrancabermeja",
    "San Gil",
    "Socorro",
    "Vélez",
    "Barichara",
    "Curití",
    "Zapatoca",
    "Rionegro",
    "Cimitarra",
    "Málaga",
  ],
  SUCRE: [
    "Sincelejo",
    "Corozal",
    "San Marcos",
    "Sampués",
    "San Onofre",
    "Tolú",
    "Coveñas",
    "San Benito Abad",
    "Since",
    "Majagual",
    "Galeras",
    "Ovejas",
    "Chalán",
    "Palmito",
  ],
  TOLIMA: [
    "Ibagué",
    "Espinal",
    "Melgar",
    "Honda",
    "Chaparral",
    "Lérida",
    "Mariquita",
    "Líbano",
    "Flandes",
    "Carmen de Apicalá",
    "Purificación",
    "Guamo",
    "Planadas",
    "Coyaima",
    "Rovira",
  ],
  "VALLE DEL CAUCA": [
    "Cali",
    "Palmira",
    "Buenaventura",
    "Tuluá",
    "Cartago",
    "Jamundí",
    "Buga",
    "Candelaria",
    "Zarzal",
    "Dagua",
    "Yumbo",
    "Sevilla",
    "Pradera",
    "Florida",
    "La Unión",
  ],
  VAUPÉS: ["Mitú", "Carurú", "Pacoa", "Taraira", "Papunaua", "Yavaraté"],
  VICHADA: ["Puerto Carreño", "Cumaribo", "La Primavera", "Santa Rosalía"],
};
